# Generated by Django 4.2 on 2024-11-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('reference_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaceTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField()),
                ('focus', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('skin_condition', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_tests', to='face_ai.user')),
            ],
        ),
    ]
