# Generated by Django 4.2 on 2024-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_ai', '0002_facetest_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetest',
            name='processed_allergy',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
        migrations.AddField(
            model_name='facetest',
            name='processed_freckles',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
    ]
